### PR TITLE
Fix various url related fixes

### LINKED ISSUE #578: Bug: Various bugs with query input over the url
**Describe the bug**
- When you enter a question on the home page and submit it, the message is processed by the LLM, but the question remains in the input field.
- Long querys are leading to errors. try with long articles.
- ~Doesn't continue the existing history if you are already in a chat. Instead a fresh history is created.~

### LINKED ISSUE #589: Bug: If a query comes over an url param. the question input text is not cleared after submit
**To Reproduce**
1. go to main page
2. Write a query in the input field "hello"
3. Chat view opens
4. Text ist submitted and a response is generated.
5. The input field still contains the query "hello"

**Expected behavior**
Instead the input field should be empty. 

And the url query parameter should be cleared.

### PR DESCRIPTION
**Pull request by Meteord**
**Description**

Fixes url query parsing related bugs:
- Fixed: When you enter a question on the home page and submit it, the message is processed by the LLM, but the question remains in the input field.
- Fixed: Long querys are leading to errors. try with long articles. Especially if they contain %. 
- Fixed:  They were two user querys, one with an empty response and one with a generated one. It should only be one user query.

Testet with firefox chatbot feature.

**Reference**

Fixes #578
Fixes #589

## Summary by CodeRabbit

* **Bug Fixes**
  * More reliable parsing of questions from both hash-based and regular URL parameters on load.
  * URL cleanup now sanitizes and consistently removes question/tool-related query/hash parameters after a pending question is sent.
  * Pending-question flow is debounced and coordinated to wait for tools/data, preventing duplicate requests and re-scheduling the same question.
  * On startup, detects question URLs, clears chat state, initializes, and fetches history before sending.

### CODE REVIEW

File: mucgpt-frontend/src/pages/chat/Chat.tsx [hunk 1]
```diff
@@ -369,17 +398,17 @@ const Chat = () => {
...
                 .filter(tool => tool.trim() !== "");
             setSelectedTools(toolsArray);
         }
 
         if (questionFromUrl) {
             // If we have a question from URL, store it and wait for tools to load
-            const decodedQuestion = decodeURIComponent(questionFromUrl);
-            setQuestion(decodedQuestion);
-            setPendingQuestion(decodedQuestion);
+            const normalizedQuestion = questionFromUrl.replaceAll("+", " ");
```
Comment (simonhir) [inline mucgpt-frontend/src/pages/chat/Chat.tsx]: Is this worth it as this replaces valid `+` chars (also all other places)
